"""Add bio and travel_preferences

Revision ID: 0d97a0e338dc
Revises: 8232e6700b89
Create Date: 2026-07-23 12:41:03.189739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d97a0e338dc'
down_revision: Union[str, Sequence[str], None] = '8232e6700b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('travel_preferences', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'travel_preferences')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
