from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List
from app.db.session import SessionLocal
from app.models.user import User
from app.models.trip import Trip
from app.models.expense import Expense
from app.models.packing import PackingItem
from app.schemas.trip import TripCreate, TripResponse, TripUpdate
from app.services.ai_provider import AIProviderService
from app.dependencies.database import get_db
from app.dependencies.auth import get_current_user

router = APIRouter(prefix="/trips", tags=["Trips"])

@router.post("/generate", response_model=TripResponse, status_code=status.HTTP_201_CREATED)
async def generate_trip(
    trip_in: TripCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Generate an AI travel itinerary based on preferences.
    Saves the generated details to the database and automatically compiles
    initial packing items and expense logs linked to the trip.
    """
    # 1. Call AI generator (OpenAI/Gemini/Mock provider)
    generated_data = await AIProviderService.generate_itinerary(
        destination=trip_in.destination,
        start_date=trip_in.start_date,
        end_date=trip_in.end_date,
        budget_level=trip_in.budget_level,
        traveler_type=trip_in.traveler_type,
        interests=trip_in.interests
    )
    
    # 2. Save the primary Trip record
    new_trip = Trip(
        user_id=current_user.id,
        title=trip_in.title,
        destination=trip_in.destination,
        start_date=trip_in.start_date,
        end_date=trip_in.end_date,
        budget_level=trip_in.budget_level,
        traveler_type=trip_in.traveler_type,
        interests=trip_in.interests,
        generated_itinerary=generated_data,
        is_draft=trip_in.is_draft
    )
    
    db.add(new_trip)
    db.commit()
    db.refresh(new_trip)
    
    # 3. Auto-populate initial Packing items from AI output
    for item in generated_data.get("packing_checklist", []):
        packing_record = PackingItem(
            trip_id=new_trip.id,
            item_name=item["item"],
            category=item["cat"],
            is_packed=False
        )
        db.add(packing_record)
        
    # 4. Auto-populate initial Expenses from AI budget estimate splits
    for exp in generated_data.get("estimated_budget_split", []):
        expense_record = Expense(
            trip_id=new_trip.id,
            category=exp["category"],
            amount=float(exp["amount"]),
            description=f"Estimated {exp['category']} cost generated by TravelMate AI",
            date=trip_in.start_date
        )
        db.add(expense_record)
        
    db.commit()
    db.refresh(new_trip)
    return new_trip

@router.get("/", response_model=List[TripResponse])
async def list_trips(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    List all trips created by the currently authenticated user.
    Suitable for user dashboard feeds.
    """
    trips = db.query(Trip).filter(Trip.user_id == current_user.id).order_by(Trip.created_at.desc()).all()
    return trips

@router.get("/{trip_id}", response_model=TripResponse)
async def get_trip(
    trip_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Retrieve specific trip details.
    Ensures that users can only access their own trips.
    """
    trip = db.query(Trip).filter(Trip.id == trip_id).first()
    if not trip:
        raise HTTPException(status_code=404, detail="Trip not found")
    if trip.user_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not authorized to access this trip")
    return trip

@router.put("/{trip_id}", response_model=TripResponse)
async def update_trip(
    trip_id: int,
    trip_update: TripUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Update specific details of an existing trip.
    Allows editing destinations, dates, budgets, or publishing drafts.
    """
    trip = db.query(Trip).filter(Trip.id == trip_id).first()
    if not trip:
        raise HTTPException(status_code=404, detail="Trip not found")
    if trip.user_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not authorized to modify this trip")
        
    # Update properties dynamically
    update_data = trip_update.model_dump(exclude_unset=True)
    for key, value in update_data.items():
        setattr(trip, key, value)
        
    db.commit()
    db.refresh(trip)
    return trip

@router.delete("/{trip_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_trip(
    trip_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Delete a trip from database.
    Deletes all cascading items (expenses, packing checklists) automatically.
    """
    trip = db.query(Trip).filter(Trip.id == trip_id).first()
    if not trip:
        raise HTTPException(status_code=404, detail="Trip not found")
    if trip.user_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not authorized to delete this trip")
        
    db.delete(trip)
    db.commit()
    return None
